# SPDX-License-Identifier: MIT

version = 1

[[annotations]]
path = [
  ".github/**",
  "README.md",
  "CHANGELOG.md",
  "CONTRIBUTING.md",
  "CODE_OF_CONDUCT.md",
  "SECURITY.md",
  "LICENSE"
]
SPDX-FileCopyrightText = "2026 Torsten Schlosser"
SPDX-License-Identifier = "MIT"
