name: Documentation

on:
  push:
    branches:
      - main
      - master
    paths:
      - "**/*.md"
      - "README.md"
      - "LICENSE"
      - ".github/**"

  pull_request:
    paths:
      - "**/*.md"
      - "README.md"
      - "LICENSE"
      - ".github/**"

jobs:
  markdown:
    name: Check Markdown
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@v24
        with:
          globs: |
            **/*.md
